### ISSUE TITLE
Написать описания для каждого сотрудника из каждого отдела

### ISSUE THREAD

**Issue by formorter** [MedvedevaAlina27/arh_project#1]
Требуется указать в каждом отделе для каждой должности описание

**Comment by formorter** [comment]
Добавить описания:
- ~~архитектор~~
 - ~~разработчик~~ 
 - ~~стажер~~
 - ~~ведущий эксперт (отдел поддержки)~~
 - ~~ведущий тестировщик~~
 - ~~специалист по ручному тестированию~~
 - ~~юзабилити специалист~~
 - ~~специалист по разработке (информационная безопасность)~~
 - ~~специалист по сетям~~
 - ~~инженер информационной безопасности~~
 - ~~методолог~~
 - ~~аналитик~~
 - ~~инженер (отдел анализа данных)~~
 P.S. - названия должностей могут ещё измениться

**Comment by MedvedevaAlina27** [comment]
Архитектор:
Занимается построением сложных IT-систем для решения бизнес-задач, помогает компании применить информационные технологии, чтобы автоматизировать и упростить бизнес-процессы, сэкономить деньги или выйти на новый уровень услуг.

**Comment by MedvedevaAlina27** [comment]
Разработчик:
Занимающийся разработкой схем, механизмов, программного обеспечения, сайтов и способен реализовать любой проект от стадии замысла до её реализации техническими средствами.

**Comment by formorter** [comment]
Стажер:
Сотрудник, находящийся на стадии обучения в компании. Деятельность в основном направлена на решение однотипных задач базового уровня, которые не требуют большого количества знаний и умений.

**Comment by formorter** [comment]
Ведущий эксперт (отдел поддержки):
Разбирается во всех нюансах работы системы. Точечно определяет где находится проблема и на каком этапе она воспроизводится. Проводит анализ работы системы и передает данные об ошибках в отдел разработки.

**Comment by Tropicos** [comment]
Методолог:
Занимается разработкой методологии управления качеством данных, разработкой и актуализацией меппингов, преобразований из систем-источников до корпоративного хранилища данных, написание методологических постановок на алгоритмы формирования аналитик, критичных для раскрытий в отчетности, разработкой спецификаций на отчеты, тестированием разработанной функциональности

**Comment by Tropicos** [comment]
Аналитик:
Принимать решения более объективно, основываясь на фактах и данных (в противовес мнению, интуиции и опыту).
Искать точки роста продукта и бизнеса.
Подразумевает работу с данными через использование SQL, Python и других языков программирования, создание дешбордов, автоматизацию процессов.

**Comment by Tropicos** [comment]
Инженер (отдел анализа данных):
Обеспечивает сбор данных и готовит их для работы аналитиков и специалистов по data science. 
Подразумевает работу с данными через использование SQL, Python и других языков программирования, создание дешбордов, автоматизацию процессов.

**Comment by neudaryu** [comment]
Юзабилити-специалист:
исследует, анализирует и совершенствует пользовательский интерфейс веб-ресурсов с целью создания более «дружелюбного» (user-friendly) интерфейса, а в конечном итоге – для получения высокой конверсии и увеличения темпов продаж.

**Comment by neudaryu** [comment]
QA-аналитик(отдел тестирования): 
является наиболее осведомленным тестировщиком в отношении приоритизации, занимается обработкой требований заказчика, принимает участие в обсуждении требований, проводит оценку влияния новых требований на уже готовую систему, является держателем всех требований по проекту, подготавливает документацию.

**Comment by neudaryu** [comment]
Специалист по ручному тестированию (Функциональный/Мануальный тестировщик):
имитируя действия пользователей, проводит исследование возможностей программного продукта с целью выявления дефектов.

**Comment by neudaryu** [comment]
Ведущий тестировщик:
Опытный сотрудник высокого уровня квалификации. Самостоятельно проводит все виды тестирования, а также успешно руководит небольшими командами тестировщиков.

**Comment by neudaryu** [comment]
Специалист по разработке(информационная безопасность):
Принимает участие в разработке программ, приложений. Занимается изучением архитектуры, готового кода, указывают на возможные ошибки, баги, уязвимости.

**Comment by neudaryu** [comment]
Специалист по сетям:
Занимается поиском стандартных и необычных новых уязвимостей в сетевых, аппаратных комплексах. Способны найти причину взлома и организовать систему с мощной защитой от кибератак.

**Comment by neudaryu** [comment]
Инженер по информационной безопасности:
Занимается администрированием сервера антивирусной защиты, мониторингом состояния клиентов, удалением вирусов, поиском уязвимостей с помощью специализированного ПО и их устранением.
